## Understanding Theorem 2.1

In [1]:
import jax
import jax.numpy as jnp

In [8]:
key = jax.random.PRNGKey(314)
timesteps = 1
n_samples = 10

r = jax.random.uniform(key, (timesteps, n_samples))

In [10]:
p = 3

In [15]:
jnp.power(jnp.sum(r ** 2, axis=1), p / 2)

Array([3.5426347], dtype=float32)

In [19]:
jnp.power(jnp.sum(jnp.abs(r) * jnp.abs(r), axis=1), p / 2)

Array([3.5426347], dtype=float32)

In [16]:
jnp.power(jnp.sum(jnp.abs(r) ** p, axis=1), p / 2)

Array([1.6429579], dtype=float32)